# Generated by Django 4.2.4 on 2023-08-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node_api", "0003_category_retail_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                ("branch_name", models.CharField(max_length=255)),
                ("ifsc_code", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
